[package]
name = "injector"
description = "Token injection and payload processing for payment connectors"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = [
    "dep:common_utils", 
    "dep:masking",
    "dep:router_env",
    "dep:async-trait",
    "dep:error-stack",
    "dep:nom",
    "dep:reqwest",
    "dep:serde",
    "dep:serde_json",
    "dep:thiserror",
    "dep:tokio",
    "dep:url"
]

serde = ["default"]
tracing-actix-web = ["default"]

[dependencies]
common_utils = { version = "0.1.0", path = "../common_utils", optional = true }
masking = { version = "0.1.0", path = "../masking", optional = true }
router_env = { version = "0.1.0", path = "../router_env", optional = true }

async-trait = { version = "0.1.88", optional = true }
error-stack = { version = "0.4.1", optional = true }
nom = { version = "7.1.3", optional = true }
reqwest = { version = "0.12.0", features = ["json", "stream"], optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1.0.140", optional = true }
thiserror = { version = "1.0.69", optional = true }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"], optional = true }
url = { version = "2.5.4", features = ["serde"], optional = true }

[lints]
workspace = true