[package]
name = "injector"
description = "Token injection and payload processing for payment connectors"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
# Default feature enables all core functionality
default = [
    "dep:hyperswitch_interfaces",
    "dep:common_utils",
    "dep:external_services",
    "dep:masking",
    "dep:router_env",
    "dep:async-trait",
    "dep:error-stack",
    "dep:nom",
    "dep:serde",
    "dep:serde_json",
    "dep:thiserror",
    "dep:tokio",
    "dep:url"
]

# Legacy compatibility features for workspace builds
v1 = []  # No-op feature for v1 compatibility - injector doesn't need v1/v2 distinction
v2 = []  # No-op feature for v2 compatibility - injector doesn't need v1/v2 distinction  
serde = []  # No-op feature for workspace compatibility - always enabled via default
tracing-actix-web = []  # No-op feature for workspace compatibility

[dependencies]
# First party crates (optional dependencies enabled by default feature)
hyperswitch_interfaces = { version = "0.1.0", path = "../hyperswitch_interfaces", optional = true }
common_utils = { version = "0.1.0", path = "../common_utils", optional = true }
external_services = { version = "0.1.0", path = "../external_services", optional = true }
masking = { version = "0.1.0", path = "../masking", optional = true }
router_env = { version = "0.1.0", path = "../router_env", optional = true }

# Third party dependencies (optional dependencies enabled by default feature)
async-trait = { version = "0.1.88", optional = true }
error-stack = { version = "0.4.1", optional = true }
nom = { version = "7.1.3", optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1.0.140", optional = true }
thiserror = { version = "1.0.69", optional = true }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"], optional = true }
url = { version = "2.5.4", features = ["serde"], optional = true }

[lints]
workspace = true