[package]
name = "injector"
description = "Token injection and payload processing for payment connectors"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
v2 = ["api_models/v2", "hyperswitch_domain_models/v2", "common_utils/v2"]

[dependencies]
# First party crates
api_models = { version = "0.1.0", path = "../api_models" }
hyperswitch_domain_models = { version = "0.1.0", path = "../hyperswitch_domain_models" }
hyperswitch_interfaces = { version = "0.1.0", path = "../hyperswitch_interfaces" }
common_utils = { version = "0.1.0", path = "../common_utils" }
common_enums = { version = "0.1.0", path = "../common_enums" }
external_services = { version = "0.1.0", path = "../external_services" }
masking = { version = "0.1.0", path = "../masking" }
router_env = { version = "0.1.0", path = "../router_env" }

# Third party dependencies
async-trait = "0.1.88"
error-stack = "0.4.1"
nom = "7.1.3"
regex = "1.11.1"
reqwest = { version = "0.11.27", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "1.0.69"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
url = { version = "2.5.4", features = ["serde"] }

[lints]
workspace = true